#!/usr/bin/env python3
#
# curtin-hooks - Minimal Curtin hooks for Fedora CoreOS (pre-built qcow2)
#
# This file serves primarily as a filesystem marker for MAAS to identify
# the root partition during deployment. For CoreOS, most configuration
# is handled by Ignition during first boot.
#
# Author: Canonical Ltd.
#
# Copyright (C) 2024 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

import os
import shutil
import sys

from curtin.log import LOG
from curtin.util import load_command_environment
from curtin.config import load_command_config


def curthook(cfg, target, state):
    """Minimal configuration for Fedora CoreOS (pre-built image)"""
    LOG.info('Running minimal curtin hooks for Fedora CoreOS')
    LOG.info('CoreOS uses Ignition for system configuration')
    LOG.info('Most setup will occur during first boot via Ignition + cloud-init')
    
    # For a pre-built CoreOS qcow2 image, we don't need to:
    # - Configure bootloader (already configured)
    # - Install packages (immutable filesystem)
    # - Setup networking (handled by cloud-init)
    # - Modify system files (Ignition handles this)
    
    LOG.info('Curtin hooks completed - system ready for deployment')


def cleanup():
    """Remove curtin-hooks directory after deployment"""
    curtin_dir = os.path.dirname(__file__)
    LOG.info(f'Cleaning up curtin directory: {curtin_dir}')
    try:
        shutil.rmtree(curtin_dir)
    except Exception as e:
        LOG.warning(f'Failed to cleanup curtin directory: {e}')


def main():
    state = load_command_environment()
    config = load_command_config(None, state)
    target = state['target']

    curthook(config, target, state)
    cleanup()


if __name__ == "__main__":
    main() 